#! /bin/sh

# -----------------------------------------------

# Autostart / Add anything here to start at power on
killall picom
sleep 0.5
picom &

killall polybar 
sleep 0.5
polybar &

kitty -e fish -c "fastfetch; exec fish" &



killall dunst
dunst &

feh --bg-scale  ~/.dotfiles/hyperbeast/wallpapers/wallpaper1.jpg
setxkbmap es 
pgrep -x sxhkd > /dev/null || sxhkd &

# -----------------------------------------------

# Workspaces / monitors
bspc monitor -d 1 2 3 4 5 6

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# -----------------------------------------------

# Padding
bspc config top_padding 10
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# -----------------------------------------------

# windows
bspc config split_ratio 0.50
bspc config window_gap 40
bspc config border_width 2
bspc config normal_border_color "#31215A"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#DA70D6"
bspc config presel_feedback_color "#355B81"
bspc config urgent_border_color "#dd2727"

# -----------------------------------------------

# Monocle
bspc config single_monocle true
bspc config gapless_monocle false    # equivalent of i3 smart gaps, which only applies gaps if theres more than 1 window
bspc config borderless_monocle false # border for when there is only 1 window (monocle)

# -----------------------------------------------

# Mouse
bspc config focus_follows_pointer true




# -----------------------------------------------

# Notification
notify-send "Bspwm status:  " &
